### ISSUE TITLE
How can you fix a diagonally squiggly line?

### ISSUE THREAD

**Issue by statkclee** [doehm/cropcircles#1]
You've developed a really great package and it's helping me a lot. However, I ran into a problem in the last step where the diagonal lines were not handled neatly.

https://github.com/bit2r/bitTomato/

![image](https://github.com/doehm/cropcircles/assets/5325425/c32295bb-201d-4bee-8be2-b5799a89b1d9)

**Comment by doehm** [comment]
Hi! Thanks for logging the issue.

I suspect this is mostly a resolution issue. What is the resolution of the original image?

There's not much that can be done about the resolution of the original image but you could fix the wiggly border by first increasing the size, cropping, and downsizing to the original size (or whatever the desired size is). Can you check if the code below fixes your issue?

```
library(magick)
path <- "path-to-your-image"

# enlarge and then crop
img_cropped <- image_read(path) |>
  image_resize('400%x400%') |>
  hex_crop(border_size = 24, border_colour = 'grey')

# downsize
image_read(img_cropped) |>
  image_resize('25%x25%')
```

**Comment by statkclee** [comment]
@doehm 

Thanks... I figured it out.
