### ISSUE TITLE
Border and Fill Colours

### ISSUE THREAD

**Issue by heerymichael** [doehm/cropcircles#2]
Hi

Really love this package and found it very useful.  Was just wondering however is it possible to have a different border and fill colour for the circle shape that the image you are cropping is placed in?

Thanks

Michael

**Comment by doehm** [comment]
Hi Michael, sorry I missed this issue.

I actually had plans to build that feature in. I'll let you know when I get around to it.

In the meantime, you could do it a more manual way by first plotting on the desired background colour and then cropping with circle_crop.

Dan

**Comment by doehm** [comment]
I've now included a parameter bg_fill which allows you to select a different fill colour. Available on Git now, CRAN soonish.

Any issues let me know!

**Comment by heerymichael** [comment]
This is fantastic - thank you very much for this!

Do you have a buy me coffee link or anything like that where I could at least give something back?

Thanks
Michael

Sent from my iPhone

On 17 Nov 2023, at 11:44, Dan Oehm ***@***.***> wrote:

﻿

I've now included a parameter bg_fill which allows you to select a different fill colour. Available on Git now, CRAN soonish.

Any issues let me know!

**Comment by doehm** [comment]
No probs! Sorry I didn't get around to it sooner.

I don't at the moment but I have been asked that a couple of times recently and was thinking of setting one up. It would be very much appreciated and I'm glad you've found it a useful package 🙂
